---
title: "Figures for: Naupliar exposure to acute warming shows no carryover ontogenetic effects on respiration, body size, or development time in the copepod Acartia tonsa"
author: Mathew Holmes-Hackerd
date: "`r Sys.Date()`"
output: 
  html_document:
          code_folding: hide
          code_download: true
          toc: true
          toc_float: true
  github_document:
          html_preview: false
          toc: true
          toc_depth: 3
---

```{r setup, include=T, message = F, warning = F, echo = F}
library(nlme)
library(survival)
library(survminer)
library(MASS)
library(knitr)

knitr::opts_chunk$set(
  echo = knitr::is_html_output(),
  fig.align = "center",
  fig.path = "../Figures/markdown/",
  message = FALSE,
  warning = FALSE,
  collapse = T,
  dev = c("png", "pdf")
)

theme_matt = function(base_size = 18,
                      dark_text = "grey20"){
  mid_text <-  monochromeR::generate_palette(dark_text, "go_lighter", n_colours = 5)[2]
  light_text <-  monochromeR::generate_palette(dark_text, "go_lighter", n_colours = 5)[3]
  
  ggpubr::theme_pubr(base_family="sans") %+replace% 
    theme(
      panel.background  = element_rect(fill="transparent", colour=NA), 
      plot.background = element_rect(fill="transparent", colour=NA), 
      legend.background = element_rect(fill="transparent", colour=NA),
      legend.key = element_rect(fill="transparent", colour=NA),
      text = element_text(colour = mid_text, lineheight = 1.1),
      title = element_text(size = base_size * 1.5,
                           colour = dark_text),
      axis.text = element_text(size = base_size,
                               colour = mid_text),
      axis.title = element_text(size = base_size * 1.2,
                                margin = margin(0, 8, 0, 0)),
      legend.text = element_text(size=base_size * 0.9),
      legend.title = element_text(size = base_size * 0.9, 
                                  face = "bold"),
      plot.margin = margin(0.25, 0.25, 0.25, 0.25,"cm")
    )
}


treatment_color_vector = c("control" = "lightskyblue",
                           "heatstress" = "tomato2")  #creates color vector

group_color_vector = c("Control" = "lightskyblue",
                       "Copepod" = "tomato2")

handling_con_color_vector = c("active" = "cadetblue1",
                              "backup" = "blue3")

handling_hs_color_vector = c("active" = "firebrick1", 
                             "backup" = "darkred")


group_color_vector1 = c("Control" = "black",
                        "Copepod" = "gold")
```

```{r Making_Surv_Figs, include=TRUE}
#Kaplan-Meier Analysis for survival, uses survminer package

# km_combined = survfit(Surv(death_day, status) ~ treatment, data = surv_data)
# 
# summary(km_combined, times = c(1:16))
# 
# S_Fig2 = ggsurvplot(
#   fit = survfit(Surv(death_day, status) ~ treatment, data = surv_data),
#   xlab = "Days", 
#   ylab = "Survival Proportion", 
#   title = "Kaplan-Meier Proportional Survival Estimates",
#   palette = c("lightskyblue", "tomato2"),
#   conf.int = TRUE, 
#   pval = FALSE,
#   ggtheme = theme_matt())
# 
# cox_model <- coxph(Surv(death_day, status) ~ treatment + replicate, data = surv_data)
# 
# summary(cox_model)
# 
# S_Fig3 = ggforest(cox_model, data = surv_data)
```

# Figures
## Figure 1   
```{r Fig1, include=TRUE, fig.width=14, fig.height=6}
tolerance = mort_data %>% 
  group_by(population, dev_temp) %>% #Breaks data down into experimental groups (populations, collections, dev. temps)
  group_modify(~ data.frame( #For each of these groups, store these values in a data frame
    "LD50" = unclass( #Use a glm to estimate TPCs and then use those TPCs to estimate LD50
      dose.p(p = 0.5, 
             glm(data = .x, survivorship ~ stress_temp, family = binomial(link = "logit")))),
    "SE" = attr( #What is the SE of the LD50 estimate
      dose.p(p = 0.5,
             glm(data = .x, survivorship ~ stress_temp, family=binomial(link = "logit"))), 
      "SE")))

# Below creates the tpc curve
tpc = ggplot(mort_data, aes(x = stress_temp, y = survivorship)) +
  geom_segment(aes(x=18, xend=tolerance$LD50, y=0.5, yend=0.5)) +
  geom_segment(aes(x=tolerance$LD50, xend=tolerance$LD50, y=0, yend=0.5)) +
  geom_point(position=position_jitter(width=0.2, height=0.02), 
             size=2, alpha = 0.5, colour = "black") + 
  geom_smooth(method = "glm", se=T, 
              method.args = list(family = "binomial"), 
              linewidth = 1.2, colour = "black") + 
  scale_y_continuous(breaks = c(0, 0.5, 1)) + 
  xlab("Stress Temperature (degrees C)") +
  ylab("Individual Survivorship") + 
  theme_matt()

#Below creates the nauplii msr boxplot
naup_resp = ggplot(data=naup_resp_rates, aes(x = temp, y = msr_B88, fill = factor(temp))) +
  geom_boxplot(outlier.size = 0.0, outlier.shape=NA) +
  geom_point(position = position_dodge(width=0.75)) +
  labs(
    x = "Temperature (C)", 
    y = "Mass-Specific Respiration \n (mL Oxygen/hour/mg Carbon)",
    fill = "Temperature")+
  scale_x_continuous(breaks = c(18, 28)) + 
  scale_fill_manual(labels = c("18", "28"), 
                    values = c("lightskyblue", "tomato2"))+
  theme_matt() +
  theme(legend.position = "none")

ggarrange(tpc, naup_resp, nrow = 1, labels = "AUTO")
```

## Figure 2   
```{r Fig2, include=TRUE, fig.width=12, fig.height=6}
axis_weights = c(400, 600, 800)
break_weights = (axis_weights^2.92 * (1.11*10^-5))

full_dataset %>% filter(group == "active")%>% drop_na(sex)%>%
  mutate(new_sex = ifelse(sex %in% c("man", "Male", "M", "MALE"), "Male", "Female")) %>%
  ggplot(aes(x=stage, y=length_um, fill=treatment)) +
  facet_grid(.~new_sex) +
  geom_boxplot(lwd=0.25, outlier.shape=NA) +
  geom_point(position = position_dodge(width=0.75), size=0.65) +
  scale_y_continuous(
    sec.axis=sec_axis(~.^2.92 * (1.11*10^-5),
                      name = "Mass (ng C)", 
                      breaks = round(break_weights, digits=0))) +
  scale_fill_manual(labels = c("Control", "Heat Stress"), 
                    values = c("lightskyblue", "tomato2")) +
  labs(x = "Copepodid Stage",
       y = "Body Length (um)",
       fill = "Experimental Group") +
  theme_bw(base_size = 18) + 
  theme(panel.grid = element_blank())
```

## Figure 3   
```{r Fig3, include=TRUE, fig.width = 12, fig.height=6 }
#Creates combined per capita and mass-specific respiration plot
plot_data = full_dataset %>% 
  filter(mass_spec_resp >= 0, group == "active")

temp_naup_resp = naup_resp_rates %>%
  filter(msr_B88>0, temp == "18") %>%
  dplyr::select(10,11)

temp_naup_resp$stage <- "n"
temp_naup_resp$treatment = "control"

names(temp_naup_resp)[2] = "mass_spec_resp"
temp_naup_resp
temp_naup_resp$resp_mL_h = temp_naup_resp$resp_mL_h * -1

temp_plot_data = plot_data %>%
  ungroup() %>%
  filter(group == "active", mass_spec_resp >0) %>%
  dplyr::select(6,11,12,13)

temp_df_resp = rbind(temp_naup_resp, temp_plot_data)
temp_df_resp$stage = factor(temp_df_resp$stage, levels = c("n", "c1", "c2", "c3", "c4", "c5", "c6"))

#Per capita respiration plot
resp_plot = ggplot(temp_df_resp, aes(x = stage, y = resp_mL_h, 
                                     fill = treatment, colour = treatment)) + 
  geom_hline(yintercept = 0, size = 1) + 
  geom_boxplot(colour = "black", outlier.shape=NA) +
  geom_point(position = position_dodge(width=0.75),
             color = "black", size=0.85) + 
  scale_fill_manual(labels = c("Control", "Heat Stress"), 
                    values = c("lightskyblue", "tomato2")) +
  labs(x = "Copepodid Stage",
       y = " Per Capita Respiration \n (mL Oxygen/hour/individual)",
       fill = "Experimental Group") +
  theme_matt() 

#Mass-specific respiration plot
mass_spec_plot = ggplot(temp_df_resp, aes(x = stage, y = mass_spec_resp, 
                                          fill = treatment, colour = treatment)) + 
  geom_hline(yintercept = 0, size = 1) + 
  geom_boxplot(colour = "black", outlier.shape=NA) +
  geom_point(position = position_dodge(width = 0.75), color = "black", size = 0.85) + 
  scale_fill_manual(values = treatment_color_vector)+ 
  labs(x = "Copepodid Stage", 
       y = "Mass-Specific Respiration \n (mL Oxygen/hour/mg C)",
       fill = "Experimental Group") +
  theme_matt()

#Combining the two plots into one figure
ggarrange(resp_plot, mass_spec_plot, nrow = 1, common.legend = T, labels = "AUTO", legend = "bottom") 
```

## Figure 4   
```{r Fig4, include=TRUE, fig.width=7, fig.height=6}
dev_time_data = molt_record %>% filter(stage %in% c("c1","c6"))%>%
  group_by(id, stage)%>%
  filter(date == min(date), group == "active")%>%
  ungroup(stage)%>%
  mutate("dev_time" = lead(days) - days)%>%
  drop_na("dev_time", "sex") %>%
  dplyr::select(-stage,-days) %>%
  separate(id, c("replicate", "id_original"), sep = "_", remove=F) %>%
  mutate(
    new_sex = ifelse(sex %in% c("man", "Male", "M", "MALE"), "Male", "Female") 
  ) 

xlabs = c("Control", "Heat Stress")

ggplot(dev_time_data, aes(x=treatment, y=dev_time, fill=treatment)) +
  geom_boxplot(outlier.shape=NA) + 
  geom_point(position=position_jitter(width=0.10, height=0.00), 
             size = 2) +
  facet_grid(.~new_sex) +
  scale_fill_manual(labels = c("Control", "Heat Stress"), 
                    values = c("lightskyblue", "tomato2")) +
  labs(x = "Treatment",
       y = "Total Development Time from C1-C6 (days)",
       fill = "Experimental Group") +
  scale_x_discrete(labels = xlabs) + 
  theme_matt() + 
  theme(legend.position = "none")
```

## Figure 5   
```{r Fig5, include=TRUE, fig.width=7, fig.height=6}
full_dataset$msr_nl = full_dataset$mass_spec_resp * 1000000 
full_dataset$weight_mgC = full_dataset$weight_ngC / 1000000

thesisdata= full_dataset %>%
  filter(mass_spec_resp > 0)

df1 = full_dataset %>%
  filter(mass_spec_resp > 0, weight_mgC>0) 

ggplot(aes(x= weight_mgC, y=mass_spec_resp), data=df1)+
  labs(x = "Mass (mg Carbon)",
       y = "Mass-Specific Respiration \n (mL Oxygen/hour/mg Carbon)") +
  geom_smooth(method = "lm", formula = (y~x)) +
  geom_point()+
  scale_x_log10()+
  scale_y_log10() +
  theme_matt()

full_dataset$resp_nl_min_ind = (full_dataset$resp_mL_h * (1*10^6) ) / 60
full_dataset$weight_mg = full_dataset$weight_ngC * (1*10^-6)


ind_slopes = df1 %>% 
  group_by(id, treatment, sex, replicate) %>% 
  summarise(slope = coef(lm(log10(mass_spec_resp) ~ log10(weight_mgC)))[2],
            n = n()) %>% 
  drop_na() %>% 
  filter(n >3) 

ind_slopes %>%  #Summarizes the individual slopes; copepods that had respiration measured at all 6 stages 
  ungroup() %>% 
  summarise(n = n(),
            mean = mean(slope),
            se = sd(slope)/sqrt(n()),
            range = paste(round(range(slope)[1], digits = 2), "to", round(range(slope)[2], digits = 2), sep = " ")) %>% 
  kable(align = "c")
```


# Tables    
## Table 1    
```{r Table1, include=T}
#Remove individuals that didnt make it to C6
plot_data = plot_data %>%
  drop_na(sex)

#Makes all relevant data a factor
plot_data$replicate <- as.factor(plot_data$replicate)
plot_data$id <- as.factor(plot_data$id)
plot_data$treatment <- as.factor(plot_data$treatment)
plot_data$stage <- as.factor(plot_data$stage)
plot_data$sex <- as.factor(plot_data$sex)
plot_data$body_length <- as.factor(plot_data$body_length)

#MUST SET THESE OPTIONS BEFORE RUNNING THE MODELS
options(contrasts=c("contr.sum","contr.poly"))

#All possible model comparisons
msr_m0 <- lme(mass_spec_resp ~ stage * sex* treatment, random = ~1|replicate/id,data = plot_data)
msr_m.1 <- update(msr_m0, weights = varIdent(form = ~1|stage))
msr_m.2 <- update(msr_m0, weights = varIdent(form = ~1|sex))
msr_m.3 <- update(msr_m0, weights = varIdent(form = ~1|treatment))
msr_m.4 <- update(msr_m0, weights = varIdent(form = ~1|stage*sex))
msr_m.5 <- update(msr_m0, weights = varIdent(form = ~1|sex*treatment))
msr_m.6 <- update(msr_m0, weights = varIdent(form = ~1|stage*treatment))
msr_m.7 <- update(msr_m0, weights = varIdent(form = ~1|stage*sex*treatment))

#Comparison of models
#anova(msr_m0,msr_m.1, msr_m.2, msr_m.3, msr_m.4, msr_m.5, msr_m.6, msr_m.7)

#Residual plot
#plot(msr_m.6)
#m.6.e <- resid(msr_m.6, type = 'pearson')

#Q-Q plot
#qqnorm(m.6.e); qqline(m.6.e, col = 2)

#Summary and stats of selected model
#summary(msr_m.6)
kable(car::Anova(msr_m.6, test="F", type = 3))
```

## Table 2    
```{r Table2, include=T}
#Recreate plot_data df
plot_data = full_dataset %>% 
  filter(mass_spec_resp >= 0, group == "active")
#Remove NAs for sex and body length 
plot_data = plot_data %>%
  drop_na(body_length)%>%
  drop_na(sex) 

#RUN THESE OPTIONS BEFORE THE MODELS
options(contrasts=c("contr.sum","contr.poly"))

#All possible model comparisons
bl_m0 <- lme(body_length ~ stage * sex * treatment, random = ~1|replicate/id, data = plot_data, control =list(msMaxIter = 1000, msMaxEval = 1000))
bl_m.1 <- update(bl_m0, weights = varIdent(form = ~1|stage))
bl_m.2 <- update(bl_m0, weights = varIdent(form = ~1|sex))
bl_m.3 <- update(bl_m0, weights = varIdent(form = ~1|treatment))
bl_m.4 <- update(bl_m0, weights = varIdent(form = ~1|stage*sex))
bl_m.5 <- update(bl_m0, weights = varIdent(form = ~1|sex*treatment))
bl_m.6 <- update(bl_m0, weights = varIdent(form = ~1|stage*treatment))
bl_m.7 <- update(bl_m0, weights = varIdent(form = ~1|stage*sex*treatment))

#Comparison of models
#anova(bl_m0,bl_m.1, bl_m.2, bl_m.3, bl_m.4, bl_m.5, bl_m.6, bl_m.7)

#Residual plot
#plot(bl_m.6)
#m.6.e <- resid(bl_m.6, type = 'pearson')

#Q-Q plot
#qqnorm(m.6.e); qqline(m.6.e, col = 2)

#Summary and stats of selected model
kable(car::Anova(bl_m.6, test="F", type = 3))
#summary(bl_m.6)
```

## Table 3    
```{r Table3, include=T}
#RUN THESE OPTIONS BEFORE MODELS
options(contrasts=c("contr.sum","contr.poly"))

#All model comparisons 
dt_m0 <- lme(dev_time ~ sex * treatment, random = ~1|replicate/id,data = dev_time_data,control = lmeControl(opt = "optim"))
dt_m.1 <- update(dt_m0, weights = varIdent(form = ~1|sex))
dt_m.2 <- update(dt_m0, weights = varIdent(form = ~1|treatment))
dt_m.3 <- update(dt_m0, weights = varIdent(form = ~1|sex*treatment))

#Comparisons of models built
#anova(dt_m0,dt_m.1, dt_m.2, dt_m.3)

#Residual plot
#plot(dt_m.3)
#m.3.e <- resid(dt_m.3, type = 'pearson')
#Q-Q plot
#qqnorm(m.3.e); qqline(m.3.e, col = 2)

#Summary and stats of selected model
#summary(dt_m.3)
kable(car::Anova(dt_m.3, test="F", type = 3))
```

# Other Statistical Tests 

```{r Mass-specific Resp vs Weight Model Tests, include=FALSE}
#Used for generating figure 5, this AIC tells us the log model best fits the mass-spec resp vs weight data.
log.model = lm(log(mass_spec_resp) ~ log(weight_mgC), data=full_dataset) 
summary(log.model)
coef(log.model)
summary(log.model)$r.squared
car::Anova(log.model)

linear.model =  lm(msr_nl ~ weight_ngC, data=full_dataset)
summary(linear.model)
coef(linear.model)
summary(linear.model)$r.squared

exp.model= lm(log(msr_nl) ~ weight_ngC, data=full_dataset) 
summary(exp.model)
coef(exp.model)
summary(exp.model)$r.squared

AIC(log.model, linear.model, exp.model)
```

# Supplemental Information
## Supp. Figure 1   
```{r S_Fig1, include=TRUE, fig.width=7, fig.height=6}
data_tidyd = o2_record %>% 
  pivot_longer(cols = starts_with(c("Test", "Control")),
               names_to = c("vial"),
               values_to = "O2") %>%  
  mutate("treatment" = if_else(str_detect(vial, "Control"), "Control", "Copepod"),                       
         vial = str_extract(vial, "[:alpha:][:digit:]"),
         "vial_id" = paste(vial, rep, sep = "_")) %>% 
  group_by(vial_id) %>% 
  arrange(Time.Min.) %>% 
  mutate("scaled_O2" = O2 / first(O2)) %>% 
  drop_na(scaled_O2)%>%
  ungroup()%>%
  mutate("label"=paste("Day", rep, sep = " "),
         "label"=fct_reorder(label,rep,min))

#Creates drawdown figure of a single experimental day
data_tidyd %>%
  filter(day_id == "R1_3_24")%>%
  ggplot(aes(x = Time.Min., y = scaled_O2, colour = treatment, group = vial)) +
  scale_color_manual(values = group_color_vector1) + 
  labs(x= "Time (min.)",
       y="Scaled Oxygen (% intitial saturation)", 
       colour = "Vial Type") +
  geom_point(size = 1) + 
  theme(panel.grid = element_blank())+
  geom_smooth(method = "lm") + 
  theme_matt()
  
```

## Supp. Figure 2   
```{r S_Fig2, include=TRUE, fig.width=7, fig.height=6}
#S_Fig2
```

## Supp. Figure 3   
```{r S_Fig3, include = TRUE, fig.width=7, fig.height=6}
#S_Fig3
```

## Supp. Table 1    
```{r S_Table1, include=T}
#Emmeans post-hoc analysis of selected body length model
kable(emmeans::emmeans(bl_m.6,  pairwise ~ stage : sex )$emmeans)
```

## Supp. Table 2    
```{r S_Table2, include=T}
c6_handling_anova = full_dataset %>%
  filter(stage == "c6")
#Comparison of C6 mass-spec resp between actively handled and handling controls

#RUN THESE OPTIONS BEFORE MODELS
options(contrasts=c("contr.sum","contr.poly"))

msrh_m0 <- lme(mass_spec_resp ~ group * sex* treatment, random = ~1|replicate/id,data = c6_handling_anova)
msrh_m.1 <- update(msrh_m0, weights = varIdent(form = ~1|stage))
msrh_m.2 <- update(msrh_m0, weights = varIdent(form = ~1|sex))
msrh_m.3 <- update(msrh_m0, weights = varIdent(form = ~1|treatment))
msrh_m.4 <- update(msrh_m0, weights = varIdent(form = ~1|stage*sex))
msrh_m.5 <- update(msrh_m0, weights = varIdent(form = ~1|sex*treatment))
msrh_m.6 <- update(msrh_m0, weights = varIdent(form = ~1|stage*treatment))
msrh_m.7 <- update(msrh_m0, weights = varIdent(form = ~1|stage*sex*treatment))

#anova(msrh_m0,msrh_m.1, msrh_m.2, msrh_m.3, msrh_m.4, msrh_m.5, msrh_m.6, msrh_m.7)

kable(car::Anova(msrh_m.4, Test="F", type = 3))
```

## Supp. Table 3    
```{r S_Table3, include=T}
#Comparison of C6 body lengths between actively handled and handling controls
blh_m0 <- lme(body_length ~ group * sex* treatment, random = ~1|replicate/id,data = c6_handling_anova)
blh_m.1 <- update(blh_m0, weights = varIdent(form = ~1|stage))
blh_m.2 <- update(blh_m0, weights = varIdent(form = ~1|sex))
blh_m.3 <- update(blh_m0, weights = varIdent(form = ~1|treatment))
blh_m.4 <- update(blh_m0, weights = varIdent(form = ~1|stage*sex))
blh_m.5 <- update(blh_m0, weights = varIdent(form = ~1|sex*treatment))
blh_m.6 <- update(blh_m0, weights = varIdent(form = ~1|stage*treatment))
blh_m.7 <- update(blh_m0, weights = varIdent(form = ~1|stage*sex*treatment))

#anova(blh_m0,blh_m.1, blh_m.2, blh_m.3, blh_m.4, blh_m.5, blh_m.6, blh_m.7)

kable(car::Anova(blh_m0, Test="F", type = 3))
```

## Supp. Table 4    
```{r S_Table4, include=T}
#Comparison of copepodid dev time between actively handled and handling controls 

#Remake dev time data df
dev_time_data = molt_record %>% filter(stage %in% c("c1","c6"))%>%
  group_by(id, stage)%>%
  filter(date == min(date))%>%
  ungroup(stage)%>%
  mutate("dev_time" = lead(days) - days)%>%
  drop_na("dev_time", "sex") %>%
  dplyr::select(-stage,-days) %>%
  separate(id, c("replicate", "id_original"), sep = "_", remove=F)

#RUN THESE OPTIONS BEFORE MODELS
options(contrasts=c("contr.sum","contr.poly"))

dth_m0 <- lme(dev_time ~ group* sex * treatment, random = ~1|replicate/id,data = dev_time_data,control = lmeControl(opt = "optim"))
dth_m.1 <- update(dth_m0, weights = varIdent(form = ~1|sex))
dth_m.2 <- update(dth_m0, weights = varIdent(form = ~1|treatment))
dth_m.3 <- update(dth_m0, weights = varIdent(form = ~1|sex*treatment))

#Comparisons of models built
#anova(dth_m0,dth_m.1, dth_m.2, dth_m.3)

#Residual plot
#plot(dth_m.3)
#m.3.e <- resid(dth_m.3, type = 'pearson')
#Q-Q plot
#qqnorm(m.3.e); qqline(m.3.e, col = 2)

#Summary and stats of selected model
#summary(dth_m.3)
kable(car::Anova(dth_m.3, test="F", type = 3))
```




